/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthNotificationsRouteImport } from './routes/_auth/notifications'
import { Route as AuthExploreRouteImport } from './routes/_auth/explore'
import { Route as AuthCreateStoryRouteImport } from './routes/_auth/create-story'
import { Route as AuthCreatePostRouteImport } from './routes/_auth/create-post'
import { Route as AuthCreatePlanRouteImport } from './routes/_auth/create-plan'
import { Route as AuthUsernameRouteImport } from './routes/_auth/$username'
import { Route as AuthPlanIdRouteImport } from './routes/_auth/plan.$id'
import { Route as AuthUsernameSlugRouteImport } from './routes/_auth/$username.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificationsRoute = AuthNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExploreRoute = AuthExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreateStoryRoute = AuthCreateStoryRouteImport.update({
  id: '/create-story',
  path: '/create-story',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreatePostRoute = AuthCreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreatePlanRoute = AuthCreatePlanRouteImport.update({
  id: '/create-plan',
  path: '/create-plan',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsernameRoute = AuthUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPlanIdRoute = AuthPlanIdRouteImport.update({
  id: '/plan/$id',
  path: '/plan/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsernameSlugRoute = AuthUsernameSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthUsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/$username': typeof AuthUsernameRouteWithChildren
  '/create-plan': typeof AuthCreatePlanRoute
  '/create-post': typeof AuthCreatePostRoute
  '/create-story': typeof AuthCreateStoryRoute
  '/explore': typeof AuthExploreRoute
  '/notifications': typeof AuthNotificationsRoute
  '/profile': typeof AuthProfileRoute
  '/settings': typeof AuthSettingsRoute
  '/$username/$slug': typeof AuthUsernameSlugRoute
  '/plan/$id': typeof AuthPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/$username': typeof AuthUsernameRouteWithChildren
  '/create-plan': typeof AuthCreatePlanRoute
  '/create-post': typeof AuthCreatePostRoute
  '/create-story': typeof AuthCreateStoryRoute
  '/explore': typeof AuthExploreRoute
  '/notifications': typeof AuthNotificationsRoute
  '/profile': typeof AuthProfileRoute
  '/settings': typeof AuthSettingsRoute
  '/$username/$slug': typeof AuthUsernameSlugRoute
  '/plan/$id': typeof AuthPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/$username': typeof AuthUsernameRouteWithChildren
  '/_auth/create-plan': typeof AuthCreatePlanRoute
  '/_auth/create-post': typeof AuthCreatePostRoute
  '/_auth/create-story': typeof AuthCreateStoryRoute
  '/_auth/explore': typeof AuthExploreRoute
  '/_auth/notifications': typeof AuthNotificationsRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/$username/$slug': typeof AuthUsernameSlugRoute
  '/_auth/plan/$id': typeof AuthPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/$username'
    | '/create-plan'
    | '/create-post'
    | '/create-story'
    | '/explore'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/$username/$slug'
    | '/plan/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/$username'
    | '/create-plan'
    | '/create-post'
    | '/create-story'
    | '/explore'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/$username/$slug'
    | '/plan/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_auth'
    | '/login'
    | '/_auth/$username'
    | '/_auth/create-plan'
    | '/_auth/create-post'
    | '/_auth/create-story'
    | '/_auth/explore'
    | '/_auth/notifications'
    | '/_auth/profile'
    | '/_auth/settings'
    | '/_auth/$username/$slug'
    | '/_auth/plan/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notifications': {
      id: '/_auth/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthNotificationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/explore': {
      id: '/_auth/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthExploreRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/create-story': {
      id: '/_auth/create-story'
      path: '/create-story'
      fullPath: '/create-story'
      preLoaderRoute: typeof AuthCreateStoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/create-post': {
      id: '/_auth/create-post'
      path: '/create-post'
      fullPath: '/create-post'
      preLoaderRoute: typeof AuthCreatePostRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/create-plan': {
      id: '/_auth/create-plan'
      path: '/create-plan'
      fullPath: '/create-plan'
      preLoaderRoute: typeof AuthCreatePlanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/$username': {
      id: '/_auth/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof AuthUsernameRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/plan/$id': {
      id: '/_auth/plan/$id'
      path: '/plan/$id'
      fullPath: '/plan/$id'
      preLoaderRoute: typeof AuthPlanIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/$username/$slug': {
      id: '/_auth/$username/$slug'
      path: '/$slug'
      fullPath: '/$username/$slug'
      preLoaderRoute: typeof AuthUsernameSlugRouteImport
      parentRoute: typeof AuthUsernameRoute
    }
  }
}

interface AuthUsernameRouteChildren {
  AuthUsernameSlugRoute: typeof AuthUsernameSlugRoute
}

const AuthUsernameRouteChildren: AuthUsernameRouteChildren = {
  AuthUsernameSlugRoute: AuthUsernameSlugRoute,
}

const AuthUsernameRouteWithChildren = AuthUsernameRoute._addFileChildren(
  AuthUsernameRouteChildren,
)

interface AuthRouteChildren {
  AuthUsernameRoute: typeof AuthUsernameRouteWithChildren
  AuthCreatePlanRoute: typeof AuthCreatePlanRoute
  AuthCreatePostRoute: typeof AuthCreatePostRoute
  AuthCreateStoryRoute: typeof AuthCreateStoryRoute
  AuthExploreRoute: typeof AuthExploreRoute
  AuthNotificationsRoute: typeof AuthNotificationsRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthPlanIdRoute: typeof AuthPlanIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUsernameRoute: AuthUsernameRouteWithChildren,
  AuthCreatePlanRoute: AuthCreatePlanRoute,
  AuthCreatePostRoute: AuthCreatePostRoute,
  AuthCreateStoryRoute: AuthCreateStoryRoute,
  AuthExploreRoute: AuthExploreRoute,
  AuthNotificationsRoute: AuthNotificationsRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthPlanIdRoute: AuthPlanIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
